#!/usr/bin/env bash
# changelog.sh — Structured CHANGELOG generator from git history
# Bounty: $50 — claude-builders-bounty #1
# Usage: bash changelog.sh [since_tag] [until_ref]
#
# Auto-categorizes commits into: Added / Fixed / Changed / Removed

set -euo pipefail

SINCE="${1:-$(git describe --tags --abbrev=0 2>/dev/null || echo '')}"
UNTIL="${2:-HEAD}"
OUTPUT="CHANGELOG.md"
DATE=$(date +%Y-%m-%d)
SEP=$'\x1f'  # Unit separator — safe delimiter

# Ensure we are inside a git repo
if ! git rev-parse --git-dir >/dev/null 2>&1; then
    echo "❌ Not inside a git repository." >&2
    exit 1
fi

echo "# Changelog" > "$OUTPUT"
echo "" >> "$OUTPUT"

if [ -n "$SINCE" ]; then
    echo "## [$DATE] — $SINCE → $UNTIL" >> "$OUTPUT"
else
    echo "## [$DATE] — All commits up to $UNTIL" >> "$OUTPUT"
fi
echo "" >> "$OUTPUT"

# Fetch commits (exclude merge commits)
COMMITS=$(git log "${SINCE}..${UNTIL}" --pretty=format:"%s${SEP}%h${SEP}%an" --no-merges 2>/dev/null || git log --pretty=format:"%s${SEP}%h${SEP}%an" --no-merges)

declare -A SECTIONS
SECTIONS["Added"]=""
SECTIONS["Fixed"]=""
SECTIONS["Changed"]=""
SECTIONS["Removed"]=""

categorize() {
    local msg="$1"
    local short_hash="$2"
    local author="$3"
    local entry="- ${msg} (\`${short_hash}\`)"

    # Auto-categorization rules (case-insensitive)
    local lower_msg
    lower_msg=$(echo "$msg" | tr '[:upper:]' '[:lower:]')

    if echo "$lower_msg" | grep -qE '^(feat|add|new|implement|introduce|create)'; then
        SECTIONS["Added"]+="${entry}"$'\n'
    elif echo "$lower_msg" | grep -qE '^(fix|bug|patch|resolve|hotfix|repair|correct)'; then
        SECTIONS["Fixed"]+="${entry}"$'\n'
    elif echo "$lower_msg" | grep -qE '^(remove|delete|drop|deprecate|obsolete)'; then
        SECTIONS["Removed"]+="${entry}"$'\n'
    else
        SECTIONS["Changed"]+="${entry}"$'\n'
    fi
}

COMMIT_COUNT=0
while IFS= read -r line; do
    [ -z "$line" ] && continue
    msg="${line%%${SEP}*}"
    rest="${line#*${SEP}}"
    hash="${rest%%${SEP}*}"
    author="${rest#*${SEP}}"
    categorize "$msg" "$hash" "$author"
    COMMIT_COUNT=$((COMMIT_COUNT + 1))
done <<< "$COMMITS"

# Output sections
for section in "Added" "Changed" "Fixed" "Removed"; do
    content="${SECTIONS[$section]}"
    if [ -n "$content" ]; then
        echo "### $section" >> "$OUTPUT"
        echo "" >> "$OUTPUT"
        printf '%s' "$content" >> "$OUTPUT"
    fi
done

echo "" >> "$OUTPUT"
echo "---" >> "$OUTPUT"
echo "Generated by [changelog.sh](.) on $DATE" >> "$OUTPUT"

echo "✅ CHANGELOG.md generated with $COMMIT_COUNT commits"
