#!/usr/bin/env bash
# changelog.sh 鈥?Structured CHANGELOG generator from git history
# Bounty: $50 鈥?claude-builders-bounty #1
# Usage: bash changelog.sh [since_ref] [until_ref]
#
# Auto-categorizes commits into: Added / Fixed / Changed / Removed

set -euo pipefail

SEP=$'\x1f'  # Unit separator 鈥?safe delimiter

# Ensure we are inside a git repo
if ! git rev-parse --git-dir >/dev/null 2>&1; then
    echo "鉂?Not inside a git repository. Run from a project root." >&2
    exit 1
fi

SINCE="${1:-}"
UNTIL="${2:-HEAD}"

# Validate refs
if [ -n "$SINCE" ] && ! git rev-parse --verify "$SINCE" >/dev/null 2>&1; then
    echo "鉂?Invalid ref: $SINCE" >&2
    exit 1
fi
if ! git rev-parse --verify "$UNTIL" >/dev/null 2>&1; then
    echo "鉂?Invalid ref: $UNTIL" >&2
    exit 1
fi

# Determine commit range
if [ -n "$SINCE" ]; then
    RANGE="${SINCE}..${UNTIL}"
    RANGE_LABEL="$SINCE 鈫?$UNTIL"
else
    RANGE=""
    if tag=$(git describe --tags --abbrev=0 2>/dev/null); then
        RANGE="${tag}..${UNTIL}"
        RANGE_LABEL="$tag 鈫?$UNTIL"
    else
        RANGE_LABEL="All commits up to $UNTIL"
    fi
fi

DATE=$(date +%Y-%m-%d)
OUTPUT="CHANGELOG.md"

echo "# Changelog" > "$OUTPUT"
echo "" >> "$OUTPUT"
echo "## [$DATE] 鈥?$RANGE_LABEL" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Fetch commits (exclude merge commits)
if [ -n "$RANGE" ]; then
    COMMITS=$(git log "${RANGE}" --pretty=format:"%s${SEP}%h${SEP}%an" --no-merges 2>/dev/null)
else
    COMMITS=$(git log --pretty=format:"%s${SEP}%h${SEP}%an" --no-merges 2>/dev/null)
fi

declare -A SECTIONS
SECTIONS["Added"]=""
SECTIONS["Fixed"]=""
SECTIONS["Changed"]=""
SECTIONS["Removed"]=""

categorize() {
    local msg="$1"
    local short_hash="$2"
    local entry="- ${msg} (\`${short_hash}\`)"

    local lower_msg
    lower_msg=$(echo "$msg" | tr '[:upper:]' '[:lower:]')

    if echo "$lower_msg" | grep -qE '^(feat|add|new|implement|introduce|create)'; then
        SECTIONS["Added"]+="${entry}"$'\n'
    elif echo "$lower_msg" | grep -qE '^(fix|bug|patch|resolve|hotfix|repair|correct)'; then
        SECTIONS["Fixed"]+="${entry}"$'\n'
    elif echo "$lower_msg" | grep -qE '^(remove|delete|drop|deprecate|obsolete)'; then
        SECTIONS["Removed"]+="${entry}"$'\n'
    else
        SECTIONS["Changed"]+="${entry}"$'\n'
    fi
}

COMMIT_COUNT=0
while IFS= read -r line; do
    [ -z "$line" ] && continue
    msg="${line%%${SEP}*}"
    rest="${line#*${SEP}}"
    hash="${rest%%${SEP}*}"
    categorize "$msg" "$hash"
    COMMIT_COUNT=$((COMMIT_COUNT + 1))
done <<< "$COMMITS"

# Output sections
for section in "Added" "Changed" "Fixed" "Removed"; do
    content="${SECTIONS[$section]}"
    if [ -n "$content" ]; then
        echo "### $section" >> "$OUTPUT"
        echo "" >> "$OUTPUT"
        printf '%s' "$content" >> "$OUTPUT"
    fi
done

echo "" >> "$OUTPUT"
echo "---" >> "$OUTPUT"
echo "Generated by [changelog.sh](.) on $DATE" >> "$OUTPUT"

echo "鉁?CHANGELOG.md generated with $COMMIT_COUNT commits"
