#!/usr/bin/env bash
# generate-changelog.sh — Structured CHANGELOG generator from git history
# Bounty: $50 — claude-builders-bounty #1
# Usage: bash changelog.sh [since_tag] [until_ref]
#
# Auto-categorizes commits into: Added / Fixed / Changed / Removed

set -euo pipefail

SINCE="${1:-$(git describe --tags --abbrev=0 2>/dev/null || echo '')}"
UNTIL="${2:-HEAD}"
OUTPUT="CHANGELOG.md"
DATE=$(date +%Y-%m-%d)

echo "# Changelog" > "$OUTPUT"
echo "" >> "$OUTPUT"
echo "## [$DATE] — $SINCE → $UNTIL" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Fetch commits
COMMITS=$(git log "${SINCE}..${UNTIL}" --pretty=format:"%s|||%h|||%an" --no-merges 2>/dev/null || git log --pretty=format:"%s|||%h|||%an" --no-merges)

declare -A SECTIONS
SECTIONS["Added"]=""
SECTIONS["Fixed"]=""
SECTIONS["Changed"]=""
SECTIONS["Removed"]=""

categorize() {
    local msg="$1"
    local short_hash="$2"
    local author="$3"
    local entry="- ${msg} (${short_hash})"

    # Auto-categorization rules (case-insensitive)
    local lower_msg=$(echo "$msg" | tr '[:upper:]' '[:lower:]')

    if echo "$lower_msg" | grep -qE '^(add|feat|new|implement|introduce|create)'; then
        SECTIONS["Added"]+="${entry}"$'\n'
    elif echo "$lower_msg" | grep -qE '^(fix|bug|patch|resolve|hotfix|repair|correct)'; then
        SECTIONS["Fixed"]+="${entry}"$'\n'
    elif echo "$lower_msg" | grep -qE '^(remove|delete|drop|deprecate|obsolete)'; then
        SECTIONS["Removed"]+="${entry}"$'\n'
    else
        SECTIONS["Changed"]+="${entry}"$'\n'
    fi
}

while IFS="|||" read -r msg hash author; do
    [ -z "$msg" ] && continue
    categorize "$msg" "$hash" "$author"
done <<< "$COMMITS"

# Output sections
for section in "Added" "Changed" "Fixed" "Removed"; do
    content="${SECTIONS[$section]}"
    if [ -n "$content" ]; then
        echo "### $section" >> "$OUTPUT"
        echo "" >> "$OUTPUT"
        echo "$content" >> "$OUTPUT"
    fi
done

echo "" >> "$OUTPUT"
echo "---" >> "$OUTPUT"
echo "Generated by [generate-changelog.sh](.) on $DATE" >> "$OUTPUT"

echo "✅ CHANGELOG.md generated with $(echo "$COMMITS" | wc -l) commits"
